version: "3.9"

services:
  bitcoind_dashboard:
    container_name: bitcoind_dashboard
    build: 
      context: .
      dockerfile: Dockerfile
    image: mu373/bitcoind-dashboard
    restart: always
    networks:
      - default
    ports:
      - 3000:3000


networks:
  default:
    name: bitcoin-nw
    external: true
