version: "3.9"
services:
  bitcoind_dashboard:
    container_name: bitcoind_dashboard
    build: 
      context: .
      dockerfile: Dockerfile
    image: bitcoind_dashboard
    ports:
      - 3000:3000
    restart: always
  # nginx:
  #   container_name: bitcoind_dashboard_nginx
  #   image: nginx:latest
  #   restart: always
  #   ports:
  #     - 3001:3001
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - /cert.crt:/nginx/cert.crt
  #     - /cert.key:/nginx/cert.key

networks:
  default:
    name: bitcoin-nw
    external: true